// Generated by scripts/generate-release-history.py. Do not edit by hand.

extension ReleaseHistoryCatalog {
    static let generatedEntries: [ReleaseHistoryEntry] = [
        ReleaseHistoryEntry(
            version: "1.2.0",
            date: "July 19, 2026",
            headline: "Usage 增加按 tool/skill 的 token 归因",
            changes: [
                "ReleaseHistory 断言适配持续发布条目",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.1.0",
            date: "July 18, 2026",
            headline: "修复子模块远端指向(重建 Atoll fork,CppJieba 改指上游)",
            changes: [
                "release notes 列表项缩进续行并入所属条目",
                "清理旧应用名称与状态刷新",
                "重新探测活动权限状态",
                "修复状态栏周期刷新复发",
                "修复授权失败误清令牌",
            ]
        ),
        ReleaseHistoryEntry(
            version: "1.0.0",
            date: "June 1, 2026",
            headline: "重新定位为精简后的新产品起点",
            changes: [
                "以精简后的应用形态作为新的版本基线",
                "版本号从 1.0.0 重新开始，构建号重置为 1",
                "移除旧发布历史中已经下线的功能叙事",
                "后续 Git 历史等待重新初始化后再按新基线提交",
            ]
        ),
    ]
}
